spring:
  application:
    name: money-tracker
  datasource:
    url: jdbc:postgresql://money-tracked-db.cqch7nyjx4wc.eu-central-1.rds.amazonaws.com:5432/money_tracker?currentSchema=money_tracker
    username: postgres
    password: 710564QWE
authorization:
  header: Authorization
  ttl: 12H

monobank:
  api:
    url: https://api.monobank.ua
    get_client_info_path: /personal/client-info
    get_statements_path: /personal/statement
    token_header_name: X-Token
