spring:
  application:
    name: money-tracker
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

authorization:
  header: Authorization
  ttl: 12H

monobank:
  api:
    url: https://api.monobank.ua
    get_client_info_path: /personal/client-info
    get_statements_path: /personal/statement
    token_header_name: X-Token
